classdef conv_torchmangle92_Conv1d < nnet.layer.Layer & nnet.layer.Formattable & ...
        nnet.layer.AutogeneratedFromPyTorch & nnet.layer.Acceleratable
    %conv_torchmangle92_Conv1d Auto-generated custom layer
    % Auto-generated by MATLAB on 27-Feb-2025 16:39:26

    properties (Learnable)
        % Networks (type dlnetwork)

    end

    properties
        % Non-Trainable Parameters
        Constant_19
        Constant_14
        Constant_16
        Constant_32
        Constant_33
        Constant_34
        Constant_35



    end

    properties (Learnable)
        % Trainable Parameters
        Param_bias
        Param_weight
    end

    methods
        function obj = conv_torchmangle92_Conv1d(Name, Type, InputNames, OutputNames)
            obj.Name = Name;
            obj.Type = Type;
            obj.NumInputs = 1;
            obj.NumOutputs = 1;
            obj.InputNames = InputNames;
            obj.OutputNames = OutputNames;
        end

        function [convolution_21] = predict(obj,convolution_input_1)

            %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
            [convolution_input_1, convolution_input_1_format] = traced_mamba.ops.permuteToReversePyTorch(convolution_input_1, '*CT', '');

            if ~contains(convolution_input_1_format,'U')
                [convolution_input_1] = struct('value', convolution_input_1, 'rank', numel(convolution_input_1_format));
            end

            [convolution_21] = tracedPyTorchFunction(obj,convolution_input_1,false,"predict");


            [convolution_21] = traced_mamba.ops.labelWithPropagatedFormats(convolution_21, "*CT");
            convolution_21 = convolution_21.value ;

        end



        function [convolution_21] = forward(obj,convolution_input_1)

            %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
            [convolution_input_1, convolution_input_1_format] = traced_mamba.ops.permuteToReversePyTorch(convolution_input_1, '*CT', '');

            if ~contains(convolution_input_1_format,'U')
                [convolution_input_1] = struct('value', convolution_input_1, 'rank', numel(convolution_input_1_format));
            end

            [convolution_21] = tracedPyTorchFunction(obj,convolution_input_1,true,"forward");


            [convolution_21] = traced_mamba.ops.labelWithPropagatedFormats(convolution_21, "*CT");
            convolution_21 = convolution_21.value ;

        end



        function [convolution_21] = tracedPyTorchFunction(obj,convolution_input_1,isForward,predict)

            [Constant_19] = traced_mamba.ops.makeStructForConstant(int64(obj.Constant_19), int64(0), "Typed");
            [Constant_14] = traced_mamba.ops.makeStructForConstant(int64(obj.Constant_14), int64(0), "Typed");
            [Constant_16] = traced_mamba.ops.makeStructForConstant(int64(obj.Constant_16), int64(0), "Typed");
            GetAttr_bias_1 = obj.Param_bias;

            [GetAttr_bias_1] = struct('value', dlarray(GetAttr_bias_1,'UU'), 'rank', 1);

            GetAttr_weight_1 = obj.Param_weight;

            [GetAttr_weight_1] = struct('value', dlarray(GetAttr_weight_1,'UUU'), 'rank', 3);

            [Constant_32] = traced_mamba.ops.makeStructForConstant(int64(obj.Constant_32), int64(1), "Typed");
            [Constant_33] = traced_mamba.ops.makeStructForConstant(int64(obj.Constant_33), int64(1), "Typed");
            [Constant_34] = traced_mamba.ops.makeStructForConstant(int64(obj.Constant_34), int64(1), "Typed");
            [Constant_35] = traced_mamba.ops.makeStructForConstant(int64(obj.Constant_35), int64(1), "Typed");
            [convolution_21] = traced_mamba.ops.pyConvolution(convolution_input_1, GetAttr_weight_1, GetAttr_bias_1, Constant_32, Constant_33, Constant_34, Constant_14, Constant_35, Constant_16);
        end

    end
end

