classdef linear_torchmangle102_Linear < nnet.layer.Layer & nnet.layer.Formattable & ...
        nnet.layer.AutogeneratedFromPyTorch & nnet.layer.Acceleratable
    %linear_torchmangle102_Linear Auto-generated custom layer
    % Auto-generated by MATLAB on 27-Feb-2025 16:39:26

    properties (Learnable)
        % Networks (type dlnetwork)

    end

    properties
        % Non-Trainable Parameters




    end

    properties (Learnable)
        % Trainable Parameters
        Param_bias
        Param_weight
    end

    methods
        function obj = linear_torchmangle102_Linear(Name, Type, InputNames, OutputNames)
            obj.Name = Name;
            obj.Type = Type;
            obj.NumInputs = 2;
            obj.NumOutputs = 2;
            obj.InputNames = InputNames;
            obj.OutputNames = OutputNames;
        end

        function [linear_x_1, linear_x_1_rank] = predict(obj,linear_argument1_1, linear_argument1_1_rank)

            %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
            [linear_argument1_1, linear_argument1_1_format] = traced_mamba.ops.permuteToReversePyTorch(linear_argument1_1, '', numel(linear_argument1_1_rank));
            [linear_argument1_1] = struct('value', linear_argument1_1, 'rank', int64(numel(linear_argument1_1_rank)));

            [linear_x_1] = tracedPyTorchFunction(obj,linear_argument1_1,false,"predict");

            [linear_x_1_rank] = ones([1,linear_x_1.rank], 'single');
            linear_x_1_rank = dlarray(linear_x_1_rank,'UU');
            %Permute U-labelled output to forward PyTorch dimension ordering
            if(any(dims(linear_x_1.value) == 'U'))
                linear_x_1 = permute(linear_x_1.value, fliplr(1:max(2,linear_x_1.rank)));
            end

        end



        function [linear_x_1, linear_x_1_rank] = forward(obj,linear_argument1_1, linear_argument1_1_rank)

            %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
            [linear_argument1_1, linear_argument1_1_format] = traced_mamba.ops.permuteToReversePyTorch(linear_argument1_1, '', numel(linear_argument1_1_rank));
            [linear_argument1_1] = struct('value', linear_argument1_1, 'rank', int64(numel(linear_argument1_1_rank)));

            [linear_x_1] = tracedPyTorchFunction(obj,linear_argument1_1,true,"forward");

            [linear_x_1_rank] = ones([1,linear_x_1.rank], 'single');
            linear_x_1_rank = dlarray(linear_x_1_rank,'UU');
            %Permute U-labelled output to forward PyTorch dimension ordering
            if(any(dims(linear_x_1.value) == 'U'))
                linear_x_1 = permute(linear_x_1.value, fliplr(1:max(2,linear_x_1.rank)));
            end

        end



        function [linear_x_1] = tracedPyTorchFunction(obj,linear_argument1_1,isForward,predict)

            GetAttr_bias_1 = obj.Param_bias;

            [GetAttr_bias_1] = struct('value', dlarray(GetAttr_bias_1,'UU'), 'rank', 1);

            GetAttr_weight_1 = obj.Param_weight;

            [GetAttr_weight_1] = struct('value', dlarray(GetAttr_weight_1,'UU'), 'rank', 2);

            [linear_x_1] = traced_mamba.ops.pyLinear(linear_argument1_1, GetAttr_weight_1, GetAttr_bias_1);
        end

    end
end

