classdef linear_torchmangle95_Linear < nnet.layer.Layer & nnet.layer.Formattable & ...
        nnet.layer.AutogeneratedFromPyTorch & nnet.layer.Acceleratable
    %linear_torchmangle95_Linear Auto-generated custom layer
    % Auto-generated by MATLAB on 27-Feb-2025 16:39:57

    properties (Learnable)
        % Networks (type dlnetwork)

    end

    properties
        % Non-Trainable Parameters
        Constant_6



    end

    properties (Learnable)
        % Trainable Parameters
        Param_weight
    end

    methods
        function obj = linear_torchmangle95_Linear(Name, Type, InputNames, OutputNames)
            obj.Name = Name;
            obj.Type = Type;
            obj.NumInputs = 2;
            obj.NumOutputs = 2;
            obj.InputNames = InputNames;
            obj.OutputNames = OutputNames;
        end

        function [linear_7, linear_7_rank] = predict(obj,linear_input_1, linear_input_1_rank)

            %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
            [linear_input_1, linear_input_1_format] = traced_mamba.ops.permuteToReversePyTorch(linear_input_1, '', numel(linear_input_1_rank));
            [linear_input_1] = struct('value', linear_input_1, 'rank', int64(numel(linear_input_1_rank)));

            [linear_7] = tracedPyTorchFunction(obj,linear_input_1,false,"predict");

            [linear_7_rank] = ones([1,linear_7.rank], 'single');
            linear_7_rank = dlarray(linear_7_rank,'UU');
            %Permute U-labelled output to forward PyTorch dimension ordering
            if(any(dims(linear_7.value) == 'U'))
                linear_7 = permute(linear_7.value, fliplr(1:max(2,linear_7.rank)));
            end

        end



        function [linear_7, linear_7_rank] = forward(obj,linear_input_1, linear_input_1_rank)

            %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
            [linear_input_1, linear_input_1_format] = traced_mamba.ops.permuteToReversePyTorch(linear_input_1, '', numel(linear_input_1_rank));
            [linear_input_1] = struct('value', linear_input_1, 'rank', int64(numel(linear_input_1_rank)));

            [linear_7] = tracedPyTorchFunction(obj,linear_input_1,true,"forward");

            [linear_7_rank] = ones([1,linear_7.rank], 'single');
            linear_7_rank = dlarray(linear_7_rank,'UU');
            %Permute U-labelled output to forward PyTorch dimension ordering
            if(any(dims(linear_7.value) == 'U'))
                linear_7 = permute(linear_7.value, fliplr(1:max(2,linear_7.rank)));
            end

        end



        function [linear_7] = tracedPyTorchFunction(obj,linear_input_1,isForward,predict)

            [Constant_6] = traced_mamba.ops.makeStructForConstant(double(obj.Constant_6), int64(0), "Typed");
            GetAttr_weight_1 = obj.Param_weight;

            [GetAttr_weight_1] = struct('value', dlarray(GetAttr_weight_1,'UU'), 'rank', 2);

            [linear_7] = traced_mamba.ops.pyLinear(linear_input_1, GetAttr_weight_1, Constant_6);
        end

    end
end

