classdef mambamodel_torchmangle124_MambaBlock < nnet.layer.Layer & nnet.layer.Formattable & ...
        nnet.layer.AutogeneratedFromPyTorch
    %mambamodel_torchmangle124_MambaBlock Auto-generated custom layer
    % Auto-generated by MATLAB on 11-Mar-2025 11:24:56

    properties (Learnable)
        % Networks (type dlnetwork)

        Param_in_proj
        Param_conv1d
        Param_x_proj
        Param_dt_proj
        Param_out_proj
    end

    properties
        % Non-Trainable Parameters
        Constant_157
        Constant_78
        Constant_56
        Constant_54
        Constant_17
        Constant_26
        Constant_27
        Constant_37
        Constant_38
        Constant_53
        Constant_101
        Constant_132
        Constant_158



    end

    properties (Learnable)
        % Trainable Parameters
        Param_D
        Param_A_log
    end

    methods
        function obj = mambamodel_torchmangle124_MambaBlock(Name, Type, InputNames, OutputNames)
            obj.Name = Name;
            obj.Type = Type;
            obj.NumInputs = 2;
            obj.NumOutputs = 2;
            obj.InputNames = InputNames;
            obj.OutputNames = OutputNames;
        end

        function [CallMethod_147, CallMethod_147_rank] = predict(obj,size_argument1_1, size_argument1_1_rank)

            %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
            [size_argument1_1, size_argument1_1_format] = traced_mamba.ops.permuteToReversePyTorch(size_argument1_1, '', numel(size_argument1_1_rank));
            [size_argument1_1] = struct('value', size_argument1_1, 'rank', int64(numel(size_argument1_1_rank)));

            [CallMethod_147] = tracedPyTorchFunction(obj,size_argument1_1,false,"predict");

            [CallMethod_147_rank] = ones([1,CallMethod_147.rank], 'single');
            CallMethod_147_rank = dlarray(CallMethod_147_rank,'UU');
            %Permute U-labelled output to forward PyTorch dimension ordering
            if(any(dims(CallMethod_147.value) == 'U'))
                CallMethod_147 = permute(CallMethod_147.value, fliplr(1:max(2,CallMethod_147.rank)));
            end

        end



        function [CallMethod_147, CallMethod_147_rank] = forward(obj,size_argument1_1, size_argument1_1_rank)

            %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
            [size_argument1_1, size_argument1_1_format] = traced_mamba.ops.permuteToReversePyTorch(size_argument1_1, '', numel(size_argument1_1_rank));
            [size_argument1_1] = struct('value', size_argument1_1, 'rank', int64(numel(size_argument1_1_rank)));

            [CallMethod_147] = tracedPyTorchFunction(obj,size_argument1_1,true,"forward");

            [CallMethod_147_rank] = ones([1,CallMethod_147.rank], 'single');
            CallMethod_147_rank = dlarray(CallMethod_147_rank,'UU');
            %Permute U-labelled output to forward PyTorch dimension ordering
            if(any(dims(CallMethod_147.value) == 'U'))
                CallMethod_147 = permute(CallMethod_147.value, fliplr(1:max(2,CallMethod_147.rank)));
            end

        end



        function [CallMethod_147] = tracedPyTorchFunction(obj,size_argument1_1,isForward,predict)

            [Constant_157] = traced_mamba.ops.makeStructForConstant(string(obj.Constant_157), int64(0), "Typed");
            [Constant_78] = traced_mamba.ops.makeStructForConstant(int64(obj.Constant_78), int64(0), "Typed");
            [Constant_56] = traced_mamba.ops.makeStructForConstant(double(obj.Constant_56), int64(0), "Typed");
            [Constant_54] = traced_mamba.ops.makeStructForConstant(int64(obj.Constant_54), int64(0), "Typed");
            [Constant_17] = traced_mamba.ops.makeStructForConstant(int64(obj.Constant_17), int64(0), "Typed");
            [Constant_26] = traced_mamba.ops.makeStructForConstant(int64(obj.Constant_26), int64(0), "Typed");
            [Constant_27] = traced_mamba.ops.makeStructForConstant(int64(obj.Constant_27), int64(0), "Typed");
            [Constant_37] = traced_mamba.ops.makeStructForConstant(int64(obj.Constant_37), int64(0), "Typed");
            [Constant_38] = traced_mamba.ops.makeStructForConstant(int64(obj.Constant_38), int64(0), "Typed");
            [Constant_53] = traced_mamba.ops.makeStructForConstant(int64(obj.Constant_53), int64(0), "Typed");
            [Constant_101] = traced_mamba.ops.makeStructForConstant(int64(obj.Constant_101), int64(0), "Typed");
            [Constant_132] = traced_mamba.ops.makeStructForConstant(int64(obj.Constant_132), int64(0), "Typed");
            GetAttr_outproj_1 = obj.Param_out_proj;


            GetAttr_dtproj_1 = obj.Param_dt_proj;


            GetAttr_xproj_1 = obj.Param_x_proj;


            GetAttr_D_1 = obj.Param_D;

            [GetAttr_D_1] = struct('value', dlarray(GetAttr_D_1,'UU'), 'rank', 1);

            GetAttr_Alog_1 = obj.Param_A_log;

            [GetAttr_Alog_1] = struct('value', dlarray(GetAttr_Alog_1,'UU'), 'rank', 2);

            GetAttr_conv1d_1 = obj.Param_conv1d;

            GetAttr_conv1d_1_InputFormat1 = '*CT';

            GetAttr_inproj_1 = obj.Param_in_proj;


            [size_18] = traced_mamba.ops.pySize(size_argument1_1, Constant_17);
            [NumToTensor_L_1] = traced_mamba.ops.makeStructForConstant(single(size_18.value), int64([size_18.rank]), "Tensor");
            [Int_22] = traced_mamba.ops.makeStructForConstant(NumToTensor_L_1.value, int64([NumToTensor_L_1.rank]), "Integer");

            size_argument1_1_labelled = size_argument1_1;
            size_argument1_1_labelled.value = permute(size_argument1_1_labelled.value, fliplr(1:max(2,size_argument1_1_labelled.rank)));
            [CallMethod_25,CallMethod_25_rank] = GetAttr_inproj_1.(predict)(size_argument1_1_labelled.value,dlarray(ones(1,size_argument1_1.rank),'UU'));
            [CallMethod_25, CallMethod_25_format] = traced_mamba.ops.permuteToReversePyTorch(CallMethod_25, '', int64(numel(CallMethod_25_rank)));
            if ~contains(CallMethod_25_format,'U')
                [CallMethod_25] = struct('value', CallMethod_25, 'rank', numel(CallMethod_25_format));
            else
                [CallMethod_25] = struct('value', CallMethod_25, 'rank', int64(numel(CallMethod_25_rank)));
            end

            chunk_28 = cell(1, Constant_26.value);
            [chunk_28{:}] = traced_mamba.ops.pyChunk(CallMethod_25, Constant_26, Constant_27);
            chunk_28 = [chunk_28{:}];
            [ListUnpack_x_1, ListUnpack_input_1] = traced_mamba.ops.pyListUnpack(chunk_28);
            [transpose_input0_1] = traced_mamba.ops.pyTranspose(ListUnpack_x_1, Constant_17, Constant_26);

            [transpose_input0_1_labelled] = traced_mamba.ops.labelWithPropagatedFormats(transpose_input0_1, GetAttr_conv1d_1_InputFormat1);
            [CallMethod_36] = GetAttr_conv1d_1.(predict)(transpose_input0_1_labelled.value);
            [CallMethod_36, CallMethod_36_format] = traced_mamba.ops.permuteToReversePyTorch(CallMethod_36, '*CT', '');
            if ~contains(CallMethod_36_format,'U')
                [CallMethod_36] = struct('value', CallMethod_36, 'rank', numel(CallMethod_36_format));
            else
                [CallMethod_36] = struct('value', CallMethod_36, 'rank', '');
            end

            [slice_40] = traced_mamba.ops.pySlice(CallMethod_36, Constant_37, Constant_37, Constant_38, Constant_17, false);
            [slice_43] = traced_mamba.ops.pySlice(slice_40, Constant_17, Constant_37, Constant_38, Constant_17, false);
            [slice_x0_1] = traced_mamba.ops.pySlice(slice_43, Constant_26, Constant_37, Int_22, Constant_17, false);
            [transpose_input1_1] = traced_mamba.ops.pyTranspose(slice_x0_1, Constant_17, Constant_26);
            [silu_input2_1] = traced_mamba.ops.pySilu(transpose_input1_1);
            [to_57] = traced_mamba.ops.pyToUnary(GetAttr_Alog_1, Constant_53, Constant_54, Constant_54, Constant_56);
            % Placeholder function for aten::exp.
            [exp_58] = traced_mamba.ops.pyAtenExp(to_57);
            [neg_A_1] = traced_mamba.ops.pyNeg(exp_58);
            [to_D0_1] = traced_mamba.ops.pyToUnary(GetAttr_D_1, Constant_53, Constant_54, Constant_54, Constant_56);

            silu_input2_1_labelled = silu_input2_1;
            silu_input2_1_labelled.value = permute(silu_input2_1_labelled.value, fliplr(1:max(2,silu_input2_1_labelled.rank)));
            [CallMethod_67,CallMethod_67_rank] = GetAttr_xproj_1.(predict)(silu_input2_1_labelled.value,dlarray(ones(1,silu_input2_1.rank),'UU'));
            [CallMethod_67, CallMethod_67_format] = traced_mamba.ops.permuteToReversePyTorch(CallMethod_67, '', int64(numel(CallMethod_67_rank)));
            if ~contains(CallMethod_67_format,'U')
                [CallMethod_67] = struct('value', CallMethod_67, 'rank', numel(CallMethod_67_format));
            else
                [CallMethod_67] = struct('value', CallMethod_67, 'rank', int64(numel(CallMethod_67_rank)));
            end

            [Constant_158] = traced_mamba.ops.makeStructForConstant(int64(obj.Constant_158), int64(1), "Typed");
            [splitwithsizes_69] = traced_mamba.ops.pySplitWithSizes(CallMethod_67, Constant_158, Constant_27);
            [ListUnpack_input3_1, ListUnpack_B_1, ListUnpack_C_1] = traced_mamba.ops.pyListUnpack(splitwithsizes_69);

            ListUnpack_input3_1_labelled = ListUnpack_input3_1;
            ListUnpack_input3_1_labelled.value = permute(ListUnpack_input3_1_labelled.value, fliplr(1:max(2,ListUnpack_input3_1_labelled.rank)));
            [CallMethod_76,CallMethod_76_rank] = GetAttr_dtproj_1.(predict)(ListUnpack_input3_1_labelled.value,dlarray(ones(1,ListUnpack_input3_1.rank),'UU'));
            [CallMethod_76, CallMethod_76_format] = traced_mamba.ops.permuteToReversePyTorch(CallMethod_76, '', int64(numel(CallMethod_76_rank)));
            if ~contains(CallMethod_76_format,'U')
                [CallMethod_76] = struct('value', CallMethod_76, 'rank', numel(CallMethod_76_format));
            else
                [CallMethod_76] = struct('value', CallMethod_76, 'rank', int64(numel(CallMethod_76_rank)));
            end

            % Placeholder function for aten::softplus.
            [softplus_delta_1] = traced_mamba.ops.pyAtenSoftplus(CallMethod_76, Constant_17, Constant_78);
            [unsqueeze_81] = traced_mamba.ops.pyUnsqueeze(softplus_delta_1, Constant_27);
            [mul_83] = traced_mamba.ops.pyElementwiseBinary(unsqueeze_81, neg_A_1, 'times');
            % Placeholder function for aten::exp.
            [exp_deltaA_1] = traced_mamba.ops.pyAtenExp(mul_83);
            [unsqueeze_87] = traced_mamba.ops.pyUnsqueeze(softplus_delta_1, Constant_27);
            [unsqueeze_89] = traced_mamba.ops.pyUnsqueeze(ListUnpack_B_1, Constant_26);
            [mul_deltaB_1] = traced_mamba.ops.pyElementwiseBinary(unsqueeze_87, unsqueeze_89, 'times');
            [unsqueeze_93] = traced_mamba.ops.pyUnsqueeze(silu_input2_1, Constant_27);
            [mul_BX_1] = traced_mamba.ops.pyElementwiseBinary(mul_deltaB_1, unsqueeze_93, 'times');
            [size_96] = traced_mamba.ops.pySize(silu_input2_1, Constant_37);
            [NumToTensor_97] = traced_mamba.ops.makeStructForConstant(single(size_96.value), int64([size_96.rank]), "Tensor");
            [Int_100] = traced_mamba.ops.makeStructForConstant(NumToTensor_97.value, int64([NumToTensor_97.rank]), "Integer");
            [ListConstruct_102] = traced_mamba.ops.pyListConstruct(Int_100, Constant_101, Constant_26);
            [zeros_h_1] = traced_mamba.ops.pyZeros(ListConstruct_102);
            [slice_111] = traced_mamba.ops.pySlice(exp_deltaA_1, Constant_37, Constant_37, Constant_38, Constant_17, false);
            [select_113_steps] = traced_mamba.ops.makeStructForConstant(int64(1), int64(0), "Typed");
            [select_113] = traced_mamba.ops.pySlice(slice_111, Constant_17, Constant_37, Constant_37, select_113_steps, true);
            [mul_115] = traced_mamba.ops.pyElementwiseBinary(select_113, zeros_h_1, 'times');
            [slice_118] = traced_mamba.ops.pySlice(mul_BX_1, Constant_37, Constant_37, Constant_38, Constant_17, false);
            [select_121_steps] = traced_mamba.ops.makeStructForConstant(int64(1), int64(0), "Typed");
            [select_121] = traced_mamba.ops.pySlice(slice_118, Constant_17, Constant_37, Constant_37, select_121_steps, true);
            [add_h0_1] = traced_mamba.ops.pyElementwiseBinary(mul_115, select_121, 'plus', Constant_17);
            [ListConstruct_125] = traced_mamba.ops.pyListConstruct(add_h0_1);
            [stack_hs_1] = traced_mamba.ops.pyStack(ListConstruct_125, Constant_17);
            [unsqueeze_129] = traced_mamba.ops.pyUnsqueeze(ListUnpack_C_1, Constant_27);
            [matmul_130] = traced_mamba.ops.pyMatmul(stack_hs_1, unsqueeze_129);
            [squeeze_y_1] = traced_mamba.ops.pySqueeze(matmul_130, Constant_132);
            [mul_137] = traced_mamba.ops.pyElementwiseBinary(to_D0_1, silu_input2_1, 'times');
            [add_y0_1] = traced_mamba.ops.pyElementwiseBinary(squeeze_y_1, mul_137, 'plus', Constant_17);
            [silu_z_1] = traced_mamba.ops.pySilu(ListUnpack_input_1);
            [mul_input4_1] = traced_mamba.ops.pyElementwiseBinary(add_y0_1, silu_z_1, 'times');

            mul_input4_1_labelled = mul_input4_1;
            mul_input4_1_labelled.value = permute(mul_input4_1_labelled.value, fliplr(1:max(2,mul_input4_1_labelled.rank)));
            [CallMethod_147,CallMethod_147_rank] = GetAttr_outproj_1.(predict)(mul_input4_1_labelled.value,dlarray(ones(1,mul_input4_1.rank),'UU'));
            [CallMethod_147, CallMethod_147_format] = traced_mamba.ops.permuteToReversePyTorch(CallMethod_147, '', int64(numel(CallMethod_147_rank)));
            if ~contains(CallMethod_147_format,'U')
                [CallMethod_147] = struct('value', CallMethod_147, 'rank', numel(CallMethod_147_format));
            else
                [CallMethod_147] = struct('value', CallMethod_147, 'rank', int64(numel(CallMethod_147_rank)));
            end

        end

    end
end

