classdef mambamodel_torchmangle97_RMSNorm < nnet.layer.Layer & nnet.layer.Formattable & ...
        nnet.layer.AutogeneratedFromPyTorch
    %mambamodel_torchmangle97_RMSNorm Auto-generated custom layer
    % Auto-generated by MATLAB on 27-Feb-2025 16:39:26

    properties (Learnable)
        % Networks (type dlnetwork)

    end

    properties
        % Non-Trainable Parameters
        Constant_15
        Constant_14
        Constant_11
        Constant_9
        Constant_5
        Constant_33



    end

    properties (Learnable)
        % Trainable Parameters
        Param_weight
    end

    methods
        function obj = mambamodel_torchmangle97_RMSNorm(Name, Type, InputNames, OutputNames)
            obj.Name = Name;
            obj.Type = Type;
            obj.NumInputs = 2;
            obj.NumOutputs = 2;
            obj.InputNames = InputNames;
            obj.OutputNames = OutputNames;
        end

        function [mul_x_1, mul_x_1_rank] = predict(obj,pow_argument1_1, pow_argument1_1_rank)

            %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
            [pow_argument1_1, pow_argument1_1_format] = traced_mamba.ops.permuteToReversePyTorch(pow_argument1_1, '', numel(pow_argument1_1_rank));
            [pow_argument1_1] = struct('value', pow_argument1_1, 'rank', int64(numel(pow_argument1_1_rank)));

            [mul_x_1] = tracedPyTorchFunction(obj,pow_argument1_1,false,"predict");

            [mul_x_1_rank] = ones([1,mul_x_1.rank], 'single');
            mul_x_1_rank = dlarray(mul_x_1_rank,'UU');
            %Permute U-labelled output to forward PyTorch dimension ordering
            if(any(dims(mul_x_1.value) == 'U'))
                mul_x_1 = permute(mul_x_1.value, fliplr(1:max(2,mul_x_1.rank)));
            end

        end



        function [mul_x_1, mul_x_1_rank] = forward(obj,pow_argument1_1, pow_argument1_1_rank)

            %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
            [pow_argument1_1, pow_argument1_1_format] = traced_mamba.ops.permuteToReversePyTorch(pow_argument1_1, '', numel(pow_argument1_1_rank));
            [pow_argument1_1] = struct('value', pow_argument1_1, 'rank', int64(numel(pow_argument1_1_rank)));

            [mul_x_1] = tracedPyTorchFunction(obj,pow_argument1_1,true,"forward");

            [mul_x_1_rank] = ones([1,mul_x_1.rank], 'single');
            mul_x_1_rank = dlarray(mul_x_1_rank,'UU');
            %Permute U-labelled output to forward PyTorch dimension ordering
            if(any(dims(mul_x_1.value) == 'U'))
                mul_x_1 = permute(mul_x_1.value, fliplr(1:max(2,mul_x_1.rank)));
            end

        end



        function [mul_x_1] = tracedPyTorchFunction(obj,pow_argument1_1,isForward,predict)

            [Constant_15] = traced_mamba.ops.makeStructForConstant(int64(obj.Constant_15), int64(0), "Typed");
            [Constant_14] = traced_mamba.ops.makeStructForConstant(single(obj.Constant_14), int64([0]), "Tensor");
            [Constant_11] = traced_mamba.ops.makeStructForConstant(double(obj.Constant_11), int64(0), "Typed");
            [Constant_9] = traced_mamba.ops.makeStructForConstant(int64(obj.Constant_9), int64(0), "Typed");
            [Constant_5] = traced_mamba.ops.makeStructForConstant(int64(obj.Constant_5), int64(0), "Typed");
            GetAttr_weight_1 = obj.Param_weight;

            [GetAttr_weight_1] = struct('value', dlarray(GetAttr_weight_1,'UU'), 'rank', 1);

            [pow_6] = traced_mamba.ops.pyElementwiseBinary(pow_argument1_1, Constant_5, 'power');
            [Constant_33] = traced_mamba.ops.makeStructForConstant(int64(obj.Constant_33), int64(1), "Typed");
            [mean_12] = traced_mamba.ops.pyMean(pow_6, Constant_33, Constant_9);
            [add_16] = traced_mamba.ops.pyElementwiseBinary(mean_12, Constant_14, 'plus', Constant_15);
            [rsqrt_17] = traced_mamba.ops.pyRsqrt(add_16);
            [mul_20] = traced_mamba.ops.pyElementwiseBinary(pow_argument1_1, rsqrt_17, 'times');
            [mul_x_1] = traced_mamba.ops.pyElementwiseBinary(mul_20, GetAttr_weight_1, 'times');
        end

    end
end

