classdef TopLevelModule_ATEN3 < nnet.layer.Layer & nnet.layer.Formattable & ...
        nnet.layer.AutogeneratedFromPyTorch & nnet.layer.Acceleratable
    %TopLevelModule_ATEN3 Auto-generated custom layer
    % Auto-generated by MATLAB on 11-Mar-2025 11:24:58

    properties (Learnable)
        % Networks (type dlnetwork)

    end

    properties
        % Non-Trainable Parameters
        Constant_9



    end

    properties (Learnable)
        % Trainable Parameters

    end

    methods
        function obj = TopLevelModule_ATEN3(Name, Type, InputNames, OutputNames)
            obj.Name = Name;
            obj.Type = Type;
            obj.NumInputs = 2;
            obj.NumOutputs = 1;
            obj.InputNames = InputNames;
            obj.OutputNames = OutputNames;
        end

        function [squeeze_19] = predict(obj,squeeze_18, squeeze_18_rank)

            %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
            [squeeze_18, squeeze_18_format] = traced_mamba.ops.permuteToReversePyTorch(squeeze_18, '', numel(squeeze_18_rank));
            [squeeze_18] = struct('value', squeeze_18, 'rank', int64(numel(squeeze_18_rank)));

            [squeeze_19] = tracedPyTorchFunction(obj,squeeze_18,false,"predict");


            %Permute U-labelled output to forward PyTorch dimension ordering
            if(any(dims(squeeze_19.value) == 'U'))
                squeeze_19 = permute(squeeze_19.value, fliplr(1:max(2,squeeze_19.rank)));
            end

        end



        function [squeeze_19] = forward(obj,squeeze_18, squeeze_18_rank)

            %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
            [squeeze_18, squeeze_18_format] = traced_mamba.ops.permuteToReversePyTorch(squeeze_18, '', numel(squeeze_18_rank));
            [squeeze_18] = struct('value', squeeze_18, 'rank', int64(numel(squeeze_18_rank)));

            [squeeze_19] = tracedPyTorchFunction(obj,squeeze_18,true,"forward");


            %Permute U-labelled output to forward PyTorch dimension ordering
            if(any(dims(squeeze_19.value) == 'U'))
                squeeze_19 = permute(squeeze_19.value, fliplr(1:max(2,squeeze_19.rank)));
            end

        end



        function [squeeze_19] = tracedPyTorchFunction(obj,squeeze_18,isForward,predict)

            [Constant_9] = traced_mamba.ops.makeStructForConstant(int64(obj.Constant_9), int64(0), "Typed");
            [squeeze_19] = traced_mamba.ops.pySqueeze(squeeze_18, Constant_9);
        end

    end
end

