classdef TopLevelModule_ATEN2 < nnet.layer.Layer & nnet.layer.Formattable & ...
        nnet.layer.AutogeneratedFromPyTorch & nnet.layer.Acceleratable
    %TopLevelModule_ATEN2 Auto-generated custom layer
    % Auto-generated by MATLAB on 11-Mar-2025 11:24:58

    properties (Learnable)
        % Networks (type dlnetwork)

    end

    properties
        % Non-Trainable Parameters
        Constant_9



    end

    properties (Learnable)
        % Trainable Parameters

    end

    methods
        function obj = TopLevelModule_ATEN2(Name, Type, InputNames, OutputNames)
            obj.Name = Name;
            obj.Type = Type;
            obj.NumInputs = 1;
            obj.NumOutputs = 1;
            obj.InputNames = InputNames;
            obj.OutputNames = OutputNames;
        end

        function [unsqueeze_input_1] = predict(obj,unsqueeze_x_1)

            %Validates that the input has the correct format and permutes its dimensions into the reverse of the original PyTorch format.
            traced_mamba.ops.validateInput(unsqueeze_x_1,3);
            [unsqueeze_x_1, unsqueeze_x_1_format] = traced_mamba.ops.permuteInputToReversePyTorch(unsqueeze_x_1, 3);
            [unsqueeze_x_1] = struct('value', unsqueeze_x_1, 'rank', int64(3));

            [unsqueeze_input_1] = tracedPyTorchFunction(obj,unsqueeze_x_1,false,"predict");


            %Permute U-labelled output to forward PyTorch dimension ordering
            if(any(dims(unsqueeze_input_1.value) == 'U'))
                unsqueeze_input_1 = permute(unsqueeze_input_1.value, fliplr(1:max(2,unsqueeze_input_1.rank)));
            end

        end



        function [unsqueeze_input_1] = forward(obj,unsqueeze_x_1)

            %Validates that the input has the correct format and permutes its dimensions into the reverse of the original PyTorch format.
            traced_mamba.ops.validateInput(unsqueeze_x_1,3);
            [unsqueeze_x_1, unsqueeze_x_1_format] = traced_mamba.ops.permuteInputToReversePyTorch(unsqueeze_x_1, 3);
            [unsqueeze_x_1] = struct('value', unsqueeze_x_1, 'rank', int64(3));

            [unsqueeze_input_1] = tracedPyTorchFunction(obj,unsqueeze_x_1,true,"forward");


            %Permute U-labelled output to forward PyTorch dimension ordering
            if(any(dims(unsqueeze_input_1.value) == 'U'))
                unsqueeze_input_1 = permute(unsqueeze_input_1.value, fliplr(1:max(2,unsqueeze_input_1.rank)));
            end

        end



        function [unsqueeze_input_1] = tracedPyTorchFunction(obj,unsqueeze_x_1,isForward,predict)

            [Constant_9] = traced_mamba.ops.makeStructForConstant(int64(obj.Constant_9), int64(0), "Typed");
            [unsqueeze_input_1] = traced_mamba.ops.pyUnsqueeze(unsqueeze_x_1, Constant_9);
        end

    end
end

