classdef x0_ATEN1 < nnet.layer.Layer & nnet.layer.Formattable & ...
        nnet.layer.AutogeneratedFromPyTorch
    %x0_ATEN1 Auto-generated custom layer
    % Auto-generated by MATLAB on 11-Mar-2025 11:24:58

    properties (Learnable)
        % Networks (type dlnetwork)

    end

    properties
        % Non-Trainable Parameters
        Constant_13



    end

    properties (Learnable)
        % Trainable Parameters

    end

    methods
        function obj = x0_ATEN1(Name, Type, InputNames, OutputNames)
            obj.Name = Name;
            obj.Type = Type;
            obj.NumInputs = 3;
            obj.NumOutputs = 2;
            obj.InputNames = InputNames;
            obj.OutputNames = OutputNames;
        end

        function [add_14, add_14_rank] = predict(obj,add_argument1_1, add_10, add_10_rank)

            %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
            [add_argument1_1, add_argument1_1_format] = traced_mamba.ops.permuteToReversePyTorch(add_argument1_1, '', 4);

            %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
            [add_10, add_10_format] = traced_mamba.ops.permuteToReversePyTorch(add_10, '', numel(add_10_rank));
            [add_argument1_1] = struct('value', add_argument1_1, 'rank', int64(4));
            [add_10] = struct('value', add_10, 'rank', int64(numel(add_10_rank)));

            [add_14] = tracedPyTorchFunction(obj,add_argument1_1, add_10,false,"predict");

            [add_14_rank] = ones([1,add_14.rank], 'single');
            add_14_rank = dlarray(add_14_rank,'UU');
            %Permute U-labelled output to forward PyTorch dimension ordering
            if(any(dims(add_14.value) == 'U'))
                add_14 = permute(add_14.value, fliplr(1:max(2,add_14.rank)));
            end

        end



        function [add_14, add_14_rank] = forward(obj,add_argument1_1, add_10, add_10_rank)

            %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
            [add_argument1_1, add_argument1_1_format] = traced_mamba.ops.permuteToReversePyTorch(add_argument1_1, '', 4);

            %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
            [add_10, add_10_format] = traced_mamba.ops.permuteToReversePyTorch(add_10, '', numel(add_10_rank));
            [add_argument1_1] = struct('value', add_argument1_1, 'rank', int64(4));
            [add_10] = struct('value', add_10, 'rank', int64(numel(add_10_rank)));

            [add_14] = tracedPyTorchFunction(obj,add_argument1_1, add_10,true,"forward");

            [add_14_rank] = ones([1,add_14.rank], 'single');
            add_14_rank = dlarray(add_14_rank,'UU');
            %Permute U-labelled output to forward PyTorch dimension ordering
            if(any(dims(add_14.value) == 'U'))
                add_14 = permute(add_14.value, fliplr(1:max(2,add_14.rank)));
            end

        end



        function [add_14] = tracedPyTorchFunction(obj,add_argument1_1, add_10,isForward,predict)

            [Constant_13] = traced_mamba.ops.makeStructForConstant(int64(obj.Constant_13), int64(0), "Typed");
            [add_14] = traced_mamba.ops.pyElementwiseBinary(add_10, add_argument1_1, 'plus', Constant_13);
        end

    end
end

